on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
name: "Test Coverage Diff"
jobs:
  Jest-Coverage-Diff:
    name: Jest Coverage Diff
    runs-on: ubuntu-latest
    steps:
     - uses: anuraag016/Jest-Coverage-Diff@V1.4
